CREATE OR REPLACE TABLE {{ var('env') }}_DB.DEMO.DBT_MODEL13 (
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	STREETADDRESS VARCHAR(150),
	CITY VARCHAR(10),
	TEST VARCHAR(10)
)

